CREATE DATABASE PROGRAMMING

CREATE TABLE LANGUAGE
(
	LANGUAGE_ID 	INT 		PRIMARY KEY,
	LANGUAGE_NAME	VARCHAR(50) 	UNIQUE NOT NULL,
	CREATER_NAME 	VARCHAR(55) 	NOT NULL,
	COUNTRY_NAME	VARCHAR(30) 	NOT NULL,
	YEAR_CREATED 	INT 		NOT NULL,
	PARADIGM 	VARCHAR(50) 	NOT NULL,
	WEBSITE		VARCHAR(99) 	NOT NULL
)

CREATE TABLE IDE
(
	IDE_ID	 	INT 		PRIMARY KEY,
	IDE_NAME 	VARCHAR(30)	NOT NULL,
	LANGUAGE_ID  	INT 		FOREIGN KEY REFERENCES LANGUAGE(LANGUAGE_ID) NOT NULL,
	RELEASE_DATE 	DATE 	 	NOT NULL,
	VERSION 	VARCHAR(30) 	NOT NULL,
	WEBSITE 	VARCHAR(99) 	NOT NULL
)

CREATE TABLE FRAMEWORK
(
	FRAMEWORK_ID 	INT 			PRIMARY KEY,
	FRAMEWORK_NAME 	VARCHAR(30) 		NOT NULL,
	LANGUAGE_ID 	INT 			FOREIGN KEY REFERENCES LANGUAGE(LANGUAGE_ID) NOT NULL,
	RELEASE_DATE 	DATE 			NOT NULL,
	VERSION		VARCHAR(30) 		NOT NULL,
	WEBSITE 	VARCHAR(99) 		NOT NULL
)

CREATE TABLE LIBRABRY
(	
	LIBRABRY_ID 	INT 			PRIMARY KEY,
	LIBRABRY_NAME	VARCHAR(30)		NOT NULL,
	DESCRIPTION 	VARCHAR(330)		NOT NULL,
	LANGUAGE_ID 	INT 			FOREIGN KEY REFERENCES LANGUAGE(LANGUAGE_ID) NOT NULL
)

CREATE TABLE PLATFORM
(
	PLATFORM_ID 	INT 			PRIMARY KEY,
	PLATFORM_NAME 	VARCHAR(30)		NOT NULL,
	DESCRIPTION 	VARCHAR(330)		NOT NULL,
	LANGUAGE_ID 	INT 			FOREIGN KEY REFERENCES LANGUAGE(LANGUAGE_ID) NOT NULL
)

CREATE TABLE COMPANY
(
	COMPANY_ID	INT		PRIMARY KEY,
	COMPANY_NAME	VARCHAR(30) 	NOT NULL,
	HEADQUARTERS	VARCHAR(30) 	NOT NULL,
	INDUSTRY	VARCHAR(35) 	NOT NULL
)
CREATE TABLE JOBS
(
	JOB_ID 		INT	 	PRIMARY KEY,
	JOB_TITLE	VARCHAR(30) 	NOT NULL,
	COMPANY_ID 	INT		FOREIGN KEY REFERENCES COMPANY(COMPANY_ID) NOT NULL,
	LANGUAGE_ID 	INT 		FOREIGN KEY REFERENCES LANGUAGE(LANGUAGE_ID) NOT NULL
)

CREATE TABLE DEVELOPER
(
	DEVELOPER_ID 	INT 		PRIMARY KEY,
	DEVELOPER_NAME	VARCHAR(30) 	NOT NULL,
	LANGUAGE_ID 	INT 		FOREIGN KEY REFERENCES LANGUAGE(LANGUAGE_ID) NOT NULL,
	PLATFORM_ID 	INT 		FOREIGN KEY REFERENCES PLATFORM(PLATFORM_ID) NOT NULL,
	EXPERIENCE 	INT 		NOT NULL,
)

CREATE TABLE USERS
(
	USER_ID 	INT 		PRIMARY KEY,
	USER_NAME	VARCHAR(30) 	NOT NULL,
	EMAIL 		VARCHAR(30) 	NOT NULL,
	LANGUAGE_ID 	INT 		FOREIGN KEY REFERENCES LANGUAGE(LANGUAGE_ID) NOT NULL
)

SELECT * FROM LANGUAGE
SELECT * FROM IDE
SELECT * FROM FRAMEWORK
SELECT * FROM LIBRABRY
SELECT * FROM PLATFORM
SELECT * FROM COMPANY
SELECT * FROM JOBS
SELECT * FROM DEVELOPER
SELECT * FROM USERS